name: nginx-thrift

ports:
  - port: 8080
    targetPort: 8080

container:
  image: sn-openresty-thrift
  imageVersion: focal
  name: nginx-thrift
  ports: 
  - containerPort: 8080
  env:
  - name: fqdn_suffix
    value: ".{{ .Release.Namespace }}.svc.cluster.local"

configMaps:
  - name: nginx.conf
    mountPath: /usr/local/openresty/nginx/conf/nginx.conf 
    value: nginx
