name: data-init-job

global:
  replicas: 1
  imagePullPolicy: "IfNotPresent"

container:
  name: data-init
  image: python
  imageVersion: "3.9-slim"
  
job:
  backoffLimit: 4
  ttlSecondsAfterFinished: 100
  restartPolicy: Never
  activeDeadlineSeconds: 900
  
# Server address for API calls (nginx service)
serverAddress: "http://nginx-web-server.{{ .Release.Namespace }}.svc.cluster.local:8080"

# Enable or disable the data initialization job
enabled: true
