name: user-service

ports:
  - port: 9090
    targetPort: 9090

container:
  command: UserService
  image: yg397/media-microservices
  name: user-service
  ports:
    - containerPort: 9090

  env:
  - name: OTEL_EXPORTER_OTLP_ENDPOINT
    value: "{{ .Values.global.opentelemetry.collectorEndpoint }}"

configMaps:
  - name: jaeger-config.yml
    mountPath: /media-microservices/config/jaeger-config.yml
    value: jaeger-config

  - name: service-config.json
    mountPath: /media-microservices/config/service-config.json
    value: service-config
