name: nginx-web-server

ports:
  - port: 8080
    targetPort: 8080

container:
  image: openresty-thrift
  imageVersion: bb5a3d2
  name: nginx-web-server
  ports:
    - containerPort: 8080
  env:
    - name: fqdn_suffix
      value: ".{{ .Release.Namespace }}.svc.cluster.local"

configMaps:
  - name: nginx.conf
    mountPath: /usr/local/openresty/nginx/conf/nginx.conf
    value: nginx
