name: post-storage-memcached

ports:
  - name: 11211
    port: 11211
    targetPort: 11211

container:
  image: library/memcached
  imageVersion: 1.6.7
  name: post-storage-memcached
  ports: 
  - containerPort: 11211

configMaps:

  - name: service-config.json
    mountPath: /social-network-microservices/config/service-config.json
    value: service-config
