name: user-timeline-service

ports:
  - port: 9090
    targetPort: 9090

container:
  command: UserTimelineService
  image: social-network-microservices
  name: user-timeline-service
  ports: 
  - containerPort: 9090

configMaps:

  - name: service-config.json
    mountPath: /social-network-microservices/config/service-config.json
    value: service-config
