name: page-service

ports:
  - port: 9090
    targetPort: 9090

container:
  command: PageService
  image: media-microservices
  name: page-service
  ports:
    - containerPort: 9090

configMaps:

  - name: service-config.json
    mountPath: /media-microservices/config/service-config.json
    value: service-config
