global:
  replicas: 1
  imagePullPolicy: "IfNotPresent"
  restartPolicy: Always
  serviceType: ClusterIP
  dockerRegistry: 10.10.10.240/library
  defaultImageVersion: latest
  nginx:
    resolverName: kube-dns.kube-system.svc.cluster.local
  otel:
    endpoint: "opentelemetry-kube-stack-deployment-collector.monitoring:4318"
    samplerParam: 1
    disabled: false
  # Jaeger config for nginx (uses Jaeger client, not OpenTelemetry)
  jaeger:
    disabled: true
    logSpans: false
    localAgentHostPort: "jaeger-agent.observability.svc.cluster.local:6831"
    queueSize: 1000
    bufferFlushInterval: 10
    samplerType: "probabilistic"
    samplerParam: 0.01
