global:
  replicas: 1
  imagePullPolicy: "IfNotPresent"
  restartPolicy: Always
  serviceType: ClusterIP
  dockerRegistry: 10.10.10.240/library
  defaultImageVersion: latest
  nginx:
    resolverName: kube-dns.kube-system.svc.cluster.local
  otel:
    endpoint: http://otel-collector.observability.svc.cluster.local:4318
    samplerParam: 0.01
    disabled: false
