global:
  replicas: 1
  imagePullPolicy: "IfNotPresent"
  restartPolicy: Always
  serviceType: ClusterIP
  dockerRegistry: 10.10.10.240/library
  defaultImageVersion: otel
  nginx:
    resolverName: kube-dns.kube-system.svc.cluster.local
  otel:
    endpoint: "opentelemetry-kube-stack-deployment-collector.monitoring:4317"
    samplerParam: 1
    disabled: false
