name: movie-id-memcached

ports:
  - port: 11211
    targetPort: 11211

container:
  image: library/memcached
  imageVersion: 1.6.7
  name: movie-id-memcached
  ports:
    - containerPort: 11211

configMaps:

  - name: service-config.json
    mountPath: /media-microservices/config/service-config.json
    value: service-config
