name: data-init-job

global:
  replicas: 1
  imagePullPolicy: "IfNotPresent"

container:
  name: data-init
  image: python
  imageVersion: "3.9-slim"
  
job:
  backoffLimit: 4
  ttlSecondsAfterFinished: 100
  restartPolicy: Never
  activeDeadlineSeconds: 10000
  hookTimeout: 10000
  
# Server address for API calls (nginx service)
serverAddress: "nginx-thrift"
serverPort: "8080"

# Social graph to use for initialization
# Options: socfb-Reed98 (default), ego-twitter, soc-twitter-follows-mun
graphName: "socfb-Reed98"

# Whether to compose posts after creating users and follows
composePosts: false

# Enable or disable the data initialization job
enabled: true
